artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AarnoStormborn/eda_ML/raw/main/attrition-dataset.zip
  local_file: artifacts/data_ingestion/data.zip

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  data_split: 0.20

data_preprocessor:
  root_dir: artifacts/data_preprocessor
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer

model_evaluation:
  experiment_id: 0

model_prediction:
  preprocessor_path: artifacts/data_preprocessor/preprocessor.pkl
  model_path: artifacts/model_trainer/model.pkl