artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AarnoStormborn/eda_ML/raw/main/attrition-dataset.zip
  local_file: artifacts/data_ingestion/data.zip

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  data_split: 0.20

data_preprocessor:
  root_dir: artifacts/data_preprocessor
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv

model_trainer:
  preprocessed_train_data: artifacts/data_preprocessor/X_train.csv
  labels: artifacts/data_preprocessor/y_train.csv
  model: randomforestclassifier

model_evaluation:
  preprocessed_test_data: artifacts/data_preprocessor/X_test.csv
  labels: artifacts/data_preprocessor/y_test.csv
  experiment_name: Attrition-Prediction
  experiment_dir_path: s3://mlflow-artifacts-harsh/1/{}/artifacts/classification_model

model_prediction:
  preprocessor_path: artifacts/data_preprocessor/preprocessor.pkl
  experiment_name: Attrition-Prediction
  experiment_dir_path: s3://mlflow-artifacts-harsh/1/{}/artifacts/classification_model